### ISSUE TITLE
Pyinstaller Generated Executable Fails on Windows 7

### ISSUE THREAD

**Issue by gp147** [BeetleChunks/redsails#3]
Installed prerequisites per README, building on Windows 7
Generated binary with unmodified repo using `pyinstaller -F --clean redSails.spec` [SUCCESS]
Running generated executable fails, and it looks like a problem with AES?:
```
C:\Repos\redsails\dist>dir
 Volume in drive C is OS
 Volume Serial Number is B053-3D1A

 Directory of C:\Repos\redsails\dist

09/28/2017  08:51 AM    <DIR>          .
09/28/2017  08:51 AM    <DIR>          ..
09/28/2017  08:51 AM    <DIR>          redSails
09/28/2017  08:51 AM         7,244,906 redSails.exe
               1 File(s)      7,244,906 bytes
               3 Dir(s)  40,497,778,688 bytes free

C:\Repos\redsails\dist>redSails.exe
Traceback (most recent call last):
  File "redSails.py", line 7, in <module>
  File "c:\users\user147\appdata\local\temp\pip-build-kpzegc\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line
 396, in load_module
  File "rsRemote\rsConnections.py", line 7, in <module>
  File "c:\users\user147\appdata\local\temp\pip-build-kpzegc\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line
 396, in load_module
  File "rsCrypto\rsCrypto.py", line 5, in <module>
  File "c:\users\user147\appdata\local\temp\pip-build-kpzegc\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line
 396, in load_module
  File "build\bdist.win32\egg\Crypto\Cipher\AES.py", line 50, in <module>
  File "c:\users\user147\appdata\local\temp\pip-build-kpzegc\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line
 396, in load_module
  File "build\bdist.win32\egg\Crypto\Cipher\_AES.py", line 7, in <module>
  File "build\bdist.win32\egg\Crypto\Cipher\_AES.py", line 6, in __bootstrap__
ImportError: DLL load failed: The specified module could not be found.
[6124] Failed to execute script redSails
```
Thanks,

GP147

**Comment by gp147** [comment]
Issue Resolved by reinstalling pycrypto from voidspace binary vs pip:

http://www.voidspace.org.uk/downloads/pycrypto26/pycrypto-2.6.win32-py2.7.exe

For some reason the version of pycrypto that pip installed did not work with Windows 7,  but installing from the voidspace binary fixed things.

Thank you,

GP147
